### ISSUE TITLE
time format

### ISSUE THREAD

**Issue by ghost** [Damko757/vut-tasker#5]
is this time format intentional?
![Screenshot 2024-11-07 122351](https://github.com/user-attachments/assets/cbbeb51a-0340-4bf2-a249-75286690815f)

**Comment by Damko757** [comment]
Yes, the time part of the format is intentional, as it does not need to show the number of seconds (it would be 00 most of the time) and 24-hour format is ISO standard.

**Comment by ghost** [comment]
sorry, i mean date
MM.d.YYYY is american format, no?

**Comment by Damko757** [comment]
The date format is actually D. M. YYYY (but could be changed to DD. MM. YYYY in the upcoming updates). 

The code for showing ISO format date can be found here: https://github.com/Damko757/vut-tasker/blob/main/web/src/extensions/String.extensions.ts

So the formatting function is in fact correct, the inputted datetime string is wrong (probably due to user inputting EU date into an US field (depends on browser settings))

**Comment by ghost** [comment]
oke, sry
